# Default configuration
spring:
  profiles:
    active: dev
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        from: tryaac1ss@gmail.com
        personal: JobPortal Security
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
  servlet:
    context-path: /

error:
  include-stacktrace: never
  include-message: always
  include-binding-errors: never

jwt:
  secret: 5ZoPtw1tCYBcri4AvOTvu8OcCgWo7iKU/HsJzMesr9M=
  expiration: 900000
  refresh:
    expiration: 2592000000

app:
  security:
    max-login-attempts: 5
    account-lock-duration-minutes: 30
    password-reset:
      token-expiration-ms: 3600000
      otp-length: 6
      max-attempts: 3


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    info:
      enabled: true
    metrics:
      enabled: true

logging:
  level:
#    org.springframework.web: INFO
#    com.jobportal.backend: INFO
    org.springframework.web: DEBUG
    org.springdoc: DEBUG
    org.springframework.security: DEBUG
    com.jobportal.backend: DEBUG