spring:
  profiles:
    active: dev
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        from: tryaac1ss@gmail.com
        personal: JobPortal Security

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080


jwt:
  secret: 5ZoPtw1tCYBcri4AvOTvu8OcCgWo7iKU/HsJzMesr9M= # Use environment variable
  # secret: ${JWT_SECRET:}
  expiration: 900000 # 15 minutes
  refresh:
    expiration: 2592000000 # 30 days

app:
  security:
    max-login-attempts: 5 # ✅ NOW USED
    account-lock-duration-minutes: 30 # ✅ NOW USED
    password-reset:
      token-expiration-ms: 3600000
      otp-length: 6
      max-attempts: 3

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.jobportal.backend.controller

logging:
  level:
    org.springframework.web: INFO
    com.jobportal.backend: INFO